name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'  # Déclenche uniquement sur les changements dans le dossier dags/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurer kubectl avec kubeconfig
      - name: Setup kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl config use-context kind-airflow-cluster

      # Copier les DAGs dans le pod du scheduler
      - name: Deploy DAGs to Airflow Scheduler
        run: |
          SCHEDULER_POD=$(kubectl get pods -n airflow -l app=airflow,component=scheduler -o jsonpath="{.items[0].metadata.name}")
          kubectl cp dags/ airflow/$SCHEDULER_POD:/opt/airflow/dags -c scheduler

      # Vérifier le déploiement
      - name: Verify deployment
        run: |
          SCHEDULER_POD=$(kubectl get pods -n airflow -l app=airflow,component=scheduler -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -n airflow $SCHEDULER_POD -c scheduler -- ls /opt/airflow/dags